# author setting
name: apibrain
author: apibrain
career: 程序员，不分前后端
baseurl: ''
description: 关于技术的总结、归纳和思考
github: http://www.github.com/apibrain
email: apibrain[at]gmail.com
# disqus: diqus-username

# website
url: http://apibrain.com/
timezone: Asia/Shanghai
permalink: /:title.html

# writing
markdown: kramdown
highlighter: rouge
# kramdown:
# input: GFM
# syntax_highlighter: rouge
# syntax_highlighter_opts:
#   line_numbers: false # bad idea, spans don't need linenos and would inherit this option
#   span:
#     line_numbers: false
#   block:
#     line_numbers: false  # set to true to show line number
#     start_line: 1

#default
# defaults:
#   - scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "default"
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
