# author setting
name: apibrain
author: apibrain
career: 无证程序员/厨师
baseurl: ''
description: 关于技术的总结、归纳和思考
github: http://www.github.com/apibrain
email: apibrain[at]gmail.com
# disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.
timezone: Asia/Shanghai
permalink: /:title.html
# highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
